name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Criamos um local único no diretório temporário para evitar o erro 128
          export THEOS_FINAL=$RUNNER_TEMP/theos_projeto
          rm -rf $THEOS_FINAL
          
          # Clona o motor principal do Theos
          git clone --recursive https://github.com/theos/theos.git $THEOS_FINAL
          
          # Remove a pasta sdks que o theos cria vazia para evitar conflito
          rm -rf $THEOS_FINAL/sdks
          
          # CLONA os SDKs (Dura uns 3-5 minutos, mas NÃO CORROMPE)
          git clone --depth 1 https://github.com/theos/sdks.git $THEOS_FINAL/sdks
          
          echo "THEOS=$THEOS_FINAL" >> $GITHUB_ENV

      - name: Build Package
        run: |
          export THEOS=${{ env.THEOS }}
          chmod -R +x $THEOS/bin
          
          # 'make clean' é o segredo para o arquivo pular de 700 bytes para o tamanho real
          make clean package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Final-FF
          path: packages/*.deb
