name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Cria um nome de pasta que muda a cada build para evitar o erro 128
          THEOS_ID="theos_$(date +%s)"
          export THEOS_PATH="$RUNNER_TEMP/$THEOS_ID"
          
          # Clona o motor Theos do zero
          git clone --recursive https://github.com/theos/theos.git $THEOS_PATH
          
          # Clona os SDKs (Método lento mas seguro contra arquivos corrompidos)
          git clone --depth 1 https://github.com/theos/sdks.git $THEOS_PATH/sdks
          
          # Salva o caminho exato para o próximo passo
          echo "THEOS_FINAL=$THEOS_PATH" >> $GITHUB_ENV

      - name: Build Package
        run: |
          export THEOS=${{ env.THEOS_FINAL }}
          chmod -R +x $THEOS/bin
          # 'make clean' obriga o sistema a gerar um arquivo real e funcional
          make clean package FINALPACKAGE=1
          
      - name: Upload Finished DEB
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Instalavel
          path: packages/*.deb
