name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Limpeza total de qualquer pasta que o GitHub tenha travado
          rm -rf $HOME/theos
          rm -rf $HOME/theos_novo
          # Instalação em um caminho totalmente novo e limpo
          git clone --recursive https://github.com/theos/theos.git $HOME/theos_final
          git clone https://github.com/theos/sdks.git $HOME/theos_final/sdks
          
      - name: Build
        run: |
          # Apontando para o novo caminho final
          export THEOS=$HOME/theos_final
          chmod -R +x $THEOS/bin
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Pronto
          path: packages/*.deb
