name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Mudando o nome da pasta para ignorar o erro de "already exists"
          git clone --recursive https://github.com/theos/theos.git $HOME/theos_novo
          git clone https://github.com/theos/sdks.git $HOME/theos_novo/sdks
          
      - name: Build
        run: |
          # Avisando ao compilador onde est√° a pasta nova
          export THEOS=$HOME/theos_novo
          chmod -R +x $THEOS/bin
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Pronto
          path: packages/*.deb
