name: Compilar
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Dependencias
        run: |
          brew install ldid
          git clone --recursive https://github.com/theos/theos.git ~/theos

      - name: Compilar
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Pronto
          path: packages/*.deb
