name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos
        run: |
          # Instala o motor direto na pasta onde o código já está (evita erro de permissão)
          git clone --recursive https://github.com/theos/theos.git ./theos_motor
          
          # Baixa o SDK direto para a pasta interna
          git clone --depth 1 https://github.com/theos/sdks.git ./theos_motor/sdks
          
          # Avisa o sistema onde o motor está escondido
          echo "THEOS=$GITHUB_WORKSPACE/theos_motor" >> $GITHUB_ENV

      - name: Build
        run: |
          export THEOS=${{ env.THEOS }}
          # Dá permissão de execução
          chmod -R +x $THEOS/bin
          # Tenta compilar
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Pronto
          path: packages/*.deb
