name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Define o local temporário
          export THEOS_DEST=$RUNNER_TEMP/theos
          
          # Clona o motor Theos
          git clone --recursive https://github.com/theos/theos.git $THEOS_DEST
          
          # CLONA os SDKs (Dura mais, mas não corrompe como o tar)
          git clone --depth 1 https://github.com/theos/sdks.git $THEOS_DEST/sdks
          
          # Salva o caminho para o próximo passo
          echo "THEOS=$THEOS_DEST" >> $GITHUB_ENV
          
      - name: Build
        run: |
          export THEOS=${{ env.THEOS }}
          chmod -R +x $THEOS/bin
          # Compila o painel
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Pronto
          path: packages/*.deb
