name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Criando um nome único baseado no tempo para nunca dar "already exists"
          FOLDER="theos_$(date +%s)"
          git clone --recursive https://github.com/theos/theos.git $HOME/$FOLDER
          git clone https://github.com/theos/sdks.git $HOME/$FOLDER/sdks
          # Salva o nome da pasta para o próximo passo
          echo "THEOS_PATH=$HOME/$FOLDER" >> $GITHUB_ENV
          
      - name: Build
        run: |
          export THEOS=${{ env.THEOS_PATH }}
          chmod -R +x $THEOS/bin
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Pronto
          path: packages/*.deb
