name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Remove lixo de tentativas anteriores para evitar o erro fatal
          rm -rf ~/theos
          # Instala o motor na pasta do usuário (sem erro de permissão)
          git clone --recursive https://github.com/theos/theos.git ~/theos
          # Baixa os SDKs oficiais
          git clone https://github.com/theos/sdks.git ~/theos/sdks
          
      - name: Build
        run: |
          export THEOS=~/theos
          # Dá permissão aos binários do motor
          chmod +x $THEOS/bin/*
          # Compila o pacote final
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Pronto
          path: packages/*.deb
