name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Limpeza total para matar o erro "Already Exists" (128)
          rm -rf $GITHUB_WORKSPACE/theos_viva
          
          # Clona o motor e os SDKs direto na pasta do projeto
          git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos_viva
          git clone --depth 1 https://github.com/theos/sdks.git $GITHUB_WORKSPACE/theos_viva/sdks
          
          # Avisa o sistema onde o motor está
          echo "THEOS=$GITHUB_WORKSPACE/theos_viva" >> $GITHUB_ENV

      - name: Build Package
        run: |
          export THEOS=${{ env.THEOS }}
          chmod -R +x $THEOS/bin
          # Força a compilação. Se o arquivo final tiver 700 bytes de novo, me avisa!
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Final-FF
          path: packages/*.deb
