name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Limpeza agressiva para matar o erro "already exists"
          rm -rf $HOME/theos
          # Instalação limpa
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          # Baixa os SDKs para a pasta correta sem conflito
          git clone https://github.com/theos/sdks.git $HOME/theos/sdks
          
      - name: Build
        run: |
          export THEOS=$HOME/theos
          # Dá permissão aos arquivos do compilador
          chmod -R +x $THEOS/bin
          # Compila o painel de vez
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Pronto
          path: packages/*.deb
