name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Limpeza garantida
          rm -rf $GITHUB_WORKSPACE/theos
          # Clone oficial do motor
          git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
          # Clone oficial dos SDKs
          git clone --depth 1 https://github.com/theos/sdks.git $GITHUB_WORKSPACE/theos/sdks

      - name: Build Package
        run: |
          # Define a vari√°vel que o comando 'make' precisa
          export THEOS=$GITHUB_WORKSPACE/theos
          chmod -R +x $THEOS/bin
          # O comando principal para gerar o arquivo real
          make package FINALPACKAGE=1
          
      - name: Upload Finished DEB
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Verdadeiro
          path: packages/*.deb
