name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Criamos um local único para evitar qualquer trava de cache do GitHub
          export THEOS=$RUNNER_TEMP/theos_final
          rm -rf $THEOS
          
          # 1. Instala o motor do Theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          
          # 2. Em vez de clonar a pasta 'sdks', vamos entrar nela e baixar o arquivo
          # Isso evita o erro "already exists" (Erro 128)
          cd $THEOS/sdks
          curl -L https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz -o sdk.tar.xz
          
          # 3. Extrai o SDK (Isolamos o erro de archive format)
          tar -xf sdk.tar.xz
          rm sdk.tar.xz
          
          echo "THEOS=$THEOS" >> $GITHUB_ENV

      - name: Build Package
        run: |
          export THEOS=${{ env.THEOS }}
          chmod -R +x $THEOS/bin
          # O 'make clean' é vital para o arquivo não vir com 700 bytes
          make clean package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Funcional-FF
          path: packages/*.deb
