name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Gera um nome de pasta único (ex: theos_123456)
          UNIQUE_FOLDER="theos_$(date +%s)"
          THEOS_PATH="$GITHUB_WORKSPACE/$UNIQUE_FOLDER"
          
          # Clona tudo nessa pasta virgem
          git clone --recursive https://github.com/theos/theos.git $THEOS_PATH
          git clone --depth 1 https://github.com/theos/sdks.git $THEOS_PATH/sdks
          
          # Passa o caminho para o próximo passo
          echo "THEOS_FINAL=$THEOS_PATH" >> $GITHUB_ENV

      - name: Build
        run: |
          export THEOS=${{ env.THEOS_FINAL }}
          chmod -R +x $THEOS/bin
          # Compila o arquivo real (30KB+)
          make package FINALPACKAGE=1
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Sem-Erro
          path: packages/*.deb
