name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Usamos um caminho novo para garantir 0 conflitos
          export THEOS_DEST=$RUNNER_TEMP/theos_viva
          rm -rf $THEOS_DEST
          
          # Clona o motor principal
          git clone --recursive https://github.com/theos/theos.git $THEOS_DEST
          
          # CLONA os SDKs (Dura uns 3 minutos, mas NÃO CORROMPE)
          git clone --depth 1 https://github.com/theos/sdks.git $THEOS_DEST/sdks
          
          echo "THEOS=$THEOS_DEST" >> $GITHUB_ENV

      - name: Build Package
        run: |
          export THEOS=${{ env.THEOS }}
          chmod -R +x $THEOS/bin
          # 'make clean' garante que o arquivo não venha vazio (700 bytes)
          make clean package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Oficial-FF
          path: packages/*.deb
