name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # APAGA QUALQUER PASTA ANTIGA ANTES DE COMEÇAR
          rm -rf ./theos_viva
          
          # Clona o motor em uma pasta com nome totalmente novo
          git clone --recursive https://github.com/theos/theos.git ./theos_viva
          
          # Limpa a pasta de SDKs interna e baixa o conteúdo de novo
          rm -rf ./theos_viva/sdks
          git clone --depth 1 https://github.com/theos/sdks.git ./theos_viva/sdks
          
          # Avisa o sistema o local exato
          echo "THEOS=$GITHUB_WORKSPACE/theos_viva" >> $GITHUB_ENV

      - name: Build
        run: |
          export THEOS=${{ env.THEOS }}
          chmod -R +x $THEOS/bin
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Pronto
          path: packages/*.deb
