name: Compilar Painel
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          
      - name: Compilar dylib
        run: |
          export THEOS=~/theos
          make package
          
      - name: Subir Arquivo
        uses: actions/upload-artifact@v3
        with:
          name: Painel-Pronto
          path: packages/*.deb
