name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Mata qualquer pasta antiga para não dar erro de "already exists"
          rm -rf $HOME/theos
          # Instala o motor do zero na pasta do usuário
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          # Baixa os SDKs oficiais para a pasta correta
          git clone https://github.com/theos/sdks.git $HOME/theos/sdks
          
      - name: Build
        run: |
          export THEOS=$HOME/theos
          # Dá permissão total aos scripts do motor
          chmod -R +x $THEOS/bin
          # Compila o arquivo final
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Pronto
          path: packages/*.deb
