name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Gera um nome único (ex: theos_1705900000) para o GitHub não travar
          THEOS_UNIQUE="theos_$(date +%s)"
          export THEOS_PATH="$RUNNER_TEMP/$THEOS_UNIQUE"
          
          echo "Instalando em local inédito: $THEOS_PATH"
          git clone --recursive https://github.com/theos/theos.git $THEOS_PATH
          
          # Baixa os SDKs (Método lento, mas que NÃO corrompe)
          git clone --depth 1 https://github.com/theos/sdks.git $THEOS_PATH/sdks
          
          # Salva o caminho para o próximo passo
          echo "THEOS=$THEOS_PATH" >> $GITHUB_ENV

      - name: Build Package
        run: |
          export THEOS=${{ env.THEOS }}
          chmod -R +x $THEOS/bin
          # 'make clean' obriga o arquivo a ter os 30KB+ reais
          make clean package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Final-FF
          path: packages/*.deb
