name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Mata qualquer pasta que esteja travando o build (Resolve o Erro 128)
          rm -rf $GITHUB_WORKSPACE/theos_final
          
          # Instalação limpa em um novo local
          git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos_final
          git clone --depth 1 https://github.com/theos/sdks.git $GITHUB_WORKSPACE/theos_final/sdks
          
          # Salva o caminho para o compilador achar
          echo "THEOS=$GITHUB_WORKSPACE/theos_final" >> $GITHUB_ENV

      - name: Build Package
        run: |
          export THEOS=${{ env.THEOS }}
          chmod -R +x $THEOS/bin
          # Força a compilação total para não vir vazio
          make package FINALPACKAGE=1
          
      - name: Upload Finished DEB
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Verdadeiro
          path: packages/*.deb
