name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # APAGA QUALQUER PASTA ANTIGA (Resolve o Erro 128 das suas fotos)
          rm -rf $GITHUB_WORKSPACE/theos_final
          
          # Instalação limpa dentro da pasta do projeto
          git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos_final
          
          # Baixa os SDKs de forma segura
          git clone --depth 1 https://github.com/theos/sdks.git $GITHUB_WORKSPACE/theos_final/sdks
          
          # Salva o caminho para o compilador não se perder
          echo "THEOS=$GITHUB_WORKSPACE/theos_final" >> $GITHUB_ENV

      - name: Build Package
        run: |
          # Usa a variável que salvamos acima
          export THEOS=${{ env.THEOS }}
          chmod -R +x $THEOS/bin
          
          # COMPILAÇÃO REAL (Isso vai fazer o arquivo ter mais de 30KB)
          make package FINALPACKAGE=1
          
      - name: Upload Finished DEB
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Real-FF
          path: packages/*.deb
