name: Compilar
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          
      - name: Compilar
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1
          
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Painel-Pronto
          path: packages/*.deb
