name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Define um local único no diretório temporário
          export THEOS_TMP=$RUNNER_TEMP/theos_final
          rm -rf $THEOS_TMP
          
          # Clona o motor Theos
          git clone --recursive https://github.com/theos/theos.git $THEOS_TMP
          
          # Em vez de curl, vamos clonar os SDKs direto (Mais seguro, sem erro de tar)
          git clone --depth 1 https://github.com/theos/sdks.git $THEOS_TMP/sdks
          
          echo "THEOS=$THEOS_TMP" >> $GITHUB_ENV

      - name: Build
        run: |
          export THEOS=${{ env.THEOS }}
          chmod -R +x $THEOS/bin
          # O clean é essencial para o arquivo não vir com 700 bytes
          make clean package FINALPACKAGE=1
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Pronto
          path: packages/*.deb
