name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Instala o Theos na pasta do usuário (evita erro de permissão)
          git clone --recursive https://github.com/theos/theos.git ~/theos
          # Baixa o SDK direto para a pasta certa
          git clone https://github.com/theos/sdks.git ~/theos/sdks
          
      - name: Build
        run: |
          export THEOS=~/theos
          # Manda o comando de compilação
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Painel-Pronto
          path: packages/*.deb
